# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        mainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        mainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(50, 50, 700, 500))
        self.background.setStyleSheet("background-color: rgb(72, 72, 108);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.tittle = QtWidgets.QLabel(self.centralwidget)
        self.tittle.setGeometry(QtCore.QRect(280, 70, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.tittle.setFont(font)
        self.tittle.setStyleSheet("background-color: rgb(72, 72, 108);\n"
                                  "color: rgb(255, 255, 255);\n"
                                  "font: 87 16pt \"Arial Black\";\n"
                                  "text-align:center;\n"
                                  "align:center;")
        self.tittle.setObjectName("tittle")
        self.inputPath = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPath.setGeometry(QtCore.QRect(160, 200, 381, 45))
        self.inputPath.setObjectName("inputPath")
        self.browse1 = QtWidgets.QPushButton(self.centralwidget)
        self.browse1.setGeometry(QtCore.QRect(550, 200, 100, 45))
        self.browse1.setStyleSheet("background-color: rgb(196, 196, 196);\n"
                                   "color: rgb(0, 0, 0);")
        self.browse1.setObjectName("browse1")
        self.outputPath = QtWidgets.QLineEdit(self.centralwidget)
        self.outputPath.setGeometry(QtCore.QRect(160, 320, 381, 45))
        self.outputPath.setObjectName("outputPath")
        self.browse2 = QtWidgets.QPushButton(self.centralwidget)
        self.browse2.setGeometry(QtCore.QRect(550, 320, 100, 45))
        self.browse2.setStyleSheet("background-color: rgb(196, 196, 196);\n"
                                   "color: rgb(0, 0, 0);")
        self.browse2.setObjectName("browse2")
        self.inputTxt = QtWidgets.QLabel(self.centralwidget)
        self.inputTxt.setGeometry(QtCore.QRect(160, 170, 200, 25))
        self.inputTxt.setStyleSheet("background-color: rgb(72, 72, 108);\n"
                                    "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                    "")
        self.inputTxt.setObjectName("inputTxt")
        self.destText = QtWidgets.QLabel(self.centralwidget)
        self.destText.setGeometry(QtCore.QRect(160, 290, 200, 25))
        self.destText.setStyleSheet("background-color: rgb(72, 72, 108);\n"
                                    "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                    "")
        self.destText.setObjectName("destText")
        self.convertBtn = QtWidgets.QPushButton(self.centralwidget)
        self.convertBtn.setGeometry(QtCore.QRect(325, 420, 150, 75))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.convertBtn.setFont(font)
        self.convertBtn.setStyleSheet("background-color: rgb(72, 72, 108);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "selection-color: rgb(85, 170, 0);\n"
                                      "border-color: rgb(255, 255, 255);\n"
                                      "font: 75 12pt \"MS Shell Dlg 2\";")
        self.convertBtn.setObjectName("convertBtn")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Any To PDF"))
        self.tittle.setText(_translate("mainWindow", "ANY TO PDF"))
        self.browse1.setText(_translate("mainWindow", "Browse"))
        self.browse2.setText(_translate("mainWindow", "Browse"))
        self.inputTxt.setText(_translate("mainWindow", "Choose your file "))
        self.destText.setText(_translate("mainWindow", "Choose destination"))
        self.convertBtn.setText(_translate("mainWindow", "CONVERT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
